version: "3.8"

services:
  zookeeper-server:
    build:
      context: .
      target: zookeeper-server

  kafka-server:
    depends_on:
    - zookeeper-server
    build:
      context: .
      target: kafka-server
    command: "--override zookeeper.connect=zookeeper-server"

  producer:
    depends_on:
    - kafka-server
    build:
      context: .
      target: rust-kafka
      args:
      - target=producer

  events:
    depends_on:
    - producer
    build:
      context: .
      target: kafka-console-consumer
    command: "--bootstrap-server kafka-server:9092 --topic events --property print.key=true"
  
  transformer:
    image: hseeberger/scala-sbt:11.0.12_1.5.5_2.13.6
    volumes:
    - ./transformer:/root
    command: /bin/bash
    tty: true

  updates:
    depends_on:
    - producer
    build:
      context: .
      target: kafka-console-consumer
    command: "--bootstrap-server kafka-server:9092 --topic updates --property print.key=true"

  consumer:
    depends_on:
    - transformer
    build:
      context: .
      target: consumer
      args:
      - target=consumer
    ports:
    - "1234:1234"
